FROM node:lts-alpine

WORKDIR /home/node/web

RUN mkdir ./node_modules && chown -R node:node node_modules

COPY package.json yarn.* ./

USER node

RUN yarn

COPY --chown=node:node . .

RUN yarn build .

EXPOSE 3000

CMD ["yarn", "start"]

