FROM node:lts-alpine

RUN mkdir -p /home/node/web && chown -R node:node /home/node/web

WORKDIR /home/node/web

RUN mkdir -p node_modules && mkdir -p build && mkdir -p public && chown -R node:node node_modules

RUN chown -R node:node build && chown -R node:node public

COPY package.json yarn.* ./

USER node

RUN yarn

COPY --chown=node:node . .

RUN yarn build .

EXPOSE 3000

CMD ["yarn", "start"]

