version: '3'

services: 
  api:
    build: .
    ports: 
      - '3333:3333'
    depends_on:
      - postgresdb
      - rediscache
    command: /bin/sh -c "yarn sequelize db:migrate && yarn start"
  web:
    build: ../frontend/.
    ports:
      - '3000:3000'
    command: yarn serve
  rediscache:
    image: redis:alpine
    ports:
      - 6379:6379
  postgresdb:
    image: postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment: 
      - "POSTGRES_PASSWORD=${proccess.env.POSTGRES_PASSWORD}"
volumes:
  postgres_data: