FROM node:lts-alpine

RUN mkdir -p /home/node/server && chown -R node:node /home/node/server

WORKDIR /home/node/server

RUN mkdir -p node_modules && chown -R node:node node_modules

USER node

RUN yarn

COPY --chown=node:node  . .

EXPOSE 3333

CMD ["yarn", "start"]